### ISSUE TITLE
Useless entries in the activity recorder

### ISSUE THREAD

**Issue by tsumaru720** [csmith/ContextApi#65]
From my experience with the Activity recorder during the past few days, it produces a number of entries that lasted for "0 seconds" which in every case have been completely incorrect. Maybe omit these results from the overall log of activities?

**Comment by csmith** [comment]
The activities are now aggregated in a slightly more sensible fashion, which should prevent one-offs from showing up so much. This also isn't really a major issue for the actual context analyser, as it can apply smooth out spurious results.
